OPENQASM 3.0;
qubit[7] Qubits;
bit[6] Results;
h Qubits[0];
h Qubits[1];
h Qubits[2];
h Qubits[3];
h Qubits[4];
h Qubits[5];
h Qubits[6];
z Qubits[6];
cx Qubits[1], Qubits[6];
cx Qubits[3], Qubits[6];
cx Qubits[5], Qubits[6];
h Qubits[5];
h Qubits[4];
h Qubits[3];
h Qubits[2];
h Qubits[1];
h Qubits[0];
Results[0] = measure Qubits[0];
Results[1] = measure Qubits[1];
Results[2] = measure Qubits[2];
Results[3] = measure Qubits[3];
Results[4] = measure Qubits[4];
Results[5] = measure Qubits[5];
