# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install tox
    - name: Run unit tests
      run: |
        tox -e unit-tests
    - name: Run AutoQASM example notebooks
      run: |
        pip install -e .
        pip install notebook matplotlib
        jupyter nbconvert --to html --execute --ExecutePreprocessor.kernel_name=python3 ./doc/examples/1_Getting_started_with_AutoQASM.ipynb
        jupyter nbconvert --to html --execute --ExecutePreprocessor.kernel_name=python3 ./doc/examples/2_Expressing_classical_control_flow.ipynb
        jupyter nbconvert --to html --execute --ExecutePreprocessor.kernel_name=python3 ./doc/examples/3_1_Iterative_phase_estimation.ipynb
        jupyter nbconvert --to html --execute --ExecutePreprocessor.kernel_name=python3 ./doc/examples/3_2_magic_state_distillation.ipynb
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: ${{ strategy.job-index == 0 }}
